# Generated by Django 3.1.6 on 2021-02-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('Network device', 'Network device'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Phone', 'Phone'), ('IT Equipment', 'IT Equipment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
