# Generated by Django 3.1.6 on 2021-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0003_auto_20210204_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('Network device', 'Network device'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Phone', 'Phone'), ('IT Equipment', 'IT Equipment')], max_length=50, null=True),
        ),
    ]
