# Generated by Django 3.1.6 on 2021-02-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0004_auto_20210204_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
