# Generated by Django 3.1.6 on 2021-02-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('IT Equipment', 'IT Equipment')], max_length=50, null=True),
        ),
    ]
