# Generated by Django 3.1.6 on 2021-02-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0014_auto_20210204_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devicemgmt.category'),
            preserve_default=False,
        ),
    ]
