# Generated by Django 3.1.6 on 2021-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0017_device_serial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
